export class CDIOyPI {


	ID_CDIO_SKILL:string;
	DESCRIPTION:string;
	CDIO_ID_CDIO:string;
	CDIO_SKILL_ID_CDIO_SKILL:string;



	constructor(ID_CDIO_SKILL:string, DESCRIPTION:string,CDIO_ID_CDIO:string,CDIO_SKILL_ID_CDIO_SKILL:string) {
		this.ID_CDIO_SKILL=ID_CDIO_SKILL;
		this.DESCRIPTION=DESCRIPTION;
		this.CDIO_ID_CDIO=CDIO_ID_CDIO;
		this.CDIO_SKILL_ID_CDIO_SKILL=CDIO_SKILL_ID_CDIO_SKILL;

	}

}