export class ParameterSmc {


	ID_PARAMETER:string;
	PARAMETER_NAME:string;
	TEXT_VALUE:string;
	PARAMETER_DESCRIPTION:string;


	constructor(ID_PARAMETER:string, PARAMETER_NAME:string,TEXT_VALUE:string,PARAMETER_DESCRIPTION:string) {
		this.ID_PARAMETER=ID_PARAMETER;
		this.PARAMETER_NAME=PARAMETER_NAME;
		this.TEXT_VALUE=TEXT_VALUE;
		this.PARAMETER_DESCRIPTION=PARAMETER_DESCRIPTION;

	}
}